services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    networks:
      - ragapp-network

  setup-qdrant:
    image: curlimages/curl:latest
    networks:
      - ragapp-network
    volumes:
      - ./scripts/create_qdrant_collection.sh:/create_qdrant_collection.sh
    command: /bin/sh -c "chmod +x /create_qdrant_collection.sh && /create_qdrant_collection.sh"
    depends_on:
      - qdrant

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434 
    volumes:
      - ./ollama:/root/.ollama
      - ./scripts/setup_ollama.sh:/setup_ollama.sh
    entrypoint: /bin/bash
    command: -c "chmod +x /setup_ollama.sh && /setup_ollama.sh"
    networks:
      - ragapp-network

  ragapp:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    environment:
      - VECTOR_STORE_PROVIDER=qdrant
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION_NAME=default
      - QDRANT_API_KEY=""
      - MODEL_PROVIDER=ollama
      - OLLAMA_BASE_URL=http://ollama:11434
      - EMBEDDING_MODEL=nomic-embed-text
      - EMBEDDING_DIM=768
    depends_on:
      - setup-qdrant
      - ollama
    networks:
      - ragapp-network
  
networks:
  ragapp-network:

