control_plane:
  port: 8000
  llm_provider: "openai"
  llm_model: "gpt-3.5-turbo"

agents:
  - name: dump_agent
    description: "I'm a storyteller."
    port: 8001
    llm_provider: "openai"
    llm_model: "gpt-3.5-turbo"
    # TODO: Looks like the prompt config is not taking effect.
    # The agent always need a tool to answer.
    prompt: "I can answer using no tool, my secret is: A baby llama is called a 'Cria'"
    tools:
      - duckduckgo