control_plane:
  port: 8000
  llm_provider: "openai"
  llm_model: "gpt-3.5-turbo"

agents:
  - name: dump_agent
    # A agent will be introduced to the control plane as a function tool call.
    # so the description is very important.
    description: "I have a name and I have a secret, let ask me a question to reveal it."
    port: 8001
    llm_provider: "openai"
    llm_model: "gpt-3.5-turbo"
    # TODO: Looks like the prompt config is not taking effect.
    prompt: "My name is RAGapp"
    tools: []